name: sdxl-pony
version: 1.0.0
base_image: effekt/runpod-comfyui:base
description: Complete SDXL and Pony Diffusion setup with all essential nodes
extends: config-base.yaml  # Inherit from base configuration

# Additional SDXL/Pony-specific nodes (will be merged with base)
nodes:
  - url: https://github.com/comfyanonymous/ComfyUI_extra_models
    description: Support for additional model architectures
  - url: https://github.com/ltdrdata/ComfyUI-Impact-Pack
    description: Impact Pack with detection and segmentation

# Additional Python requirements (will be merged with base)
requirements:
  - scipy>=1.10.0

# Workflows to include
workflows:
  - sdxl-txt2img.json
  - sdxl-img2img.json
  - pony-txt2img.json
  - pony-highres.json

# Models to download
models:
  checkpoints:
    - name: sdxl_base_1.0
      url: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors
      filename: sd_xl_base_1.0.safetensors
    - name: sdxl_refiner_1.0
      url: https://huggingface.co/stabilityai/stable-diffusion-xl-refiner-1.0/resolve/main/sd_xl_refiner_1.0.safetensors
      filename: sd_xl_refiner_1.0.safetensors
    - name: ponyDiffusionV6XL
      url: civitai:290640
      filename: ponyDiffusionV6XL.safetensors
    - name: ponyRealism
      url: civitai:372465
      filename: ponyRealism.safetensors
    - name: juggernautXL
      url: civitai:133005
      filename: juggernautXL.safetensors
  vae:
    - name: sdxl_vae
      url: https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/sdxl_vae.safetensors
      filename: sdxl_vae.safetensors
  loras:
    - name: sdxl_offset_1.0
      url: https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_offset_example-lora_1.0.safetensors
      filename: sdxl_offset_1.0.safetensors
    - name: pony_quality_boost
      url: civitai:289123
      filename: pony_quality_boost.safetensors
  upscale_models:
    - name: RealESRGAN_x4plus
      url: https://huggingface.co/ai-forever/Real-ESRGAN/resolve/main/RealESRGAN_x4plus.pth
      filename: RealESRGAN_x4plus.pth
    - name: 4x-UltraSharp
      url: https://huggingface.co/uwg/upscaler/resolve/main/ESRGAN/4x-UltraSharp.pth
      filename: 4x-UltraSharp.pth

# Environment variables (override base)
env_vars:
  DOWNLOAD_MODELS: "false"
  AUTO_UPDATE: "false"
  VARIANT_NAME: "sdxl-pony"
  COMFYUI_ARGS: ""  # Default memory management (auto) works best for 24GB cards