name: video
version: 1.0.0
base_image: effekt/runpod-comfyui:base
description: Complete video generation setup with WanVideo and AnimateDiff
extends: base.yaml  # Inherit from base configuration

# Additional video-specific nodes (will be merged with base)
nodes:
  - url: https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite
    description: Video helper suite for processing
  - url: https://github.com/Fannovel16/ComfyUI-Frame-Interpolation
    description: Frame interpolation for smoother videos
  - url: https://github.com/kijai/ComfyUI-KJNodes
    description: KJ nodes for video processing
  - url: https://github.com/FizzleDorf/ComfyUI_FizzNodes
    description: Fizz nodes for scheduling
  - url: https://github.com/ArtVentureX/comfyui-animatediff
    description: AnimateDiff integration
  - url: https://github.com/Fannovel16/ComfyUI-MotionDiff
    description: MotionDiff for motion transfer
  - url: https://github.com/kijai/ComfyUI-SUPIR
    description: SUPIR upscaling for animations
  - url: https://github.com/ltdrdata/ComfyUI-Inspire-Pack
    description: Inspire Pack utilities
  - url: https://github.com/kijai/ComfyUI-WanVideoWrapper
    description: WanVideo wrapper for Wan2.2-Animate models
  - url: https://github.com/storyicon/comfyui_segment_anything
    description: SAM2 segmentation for video masking
  - url: https://github.com/cubiq/ComfyUI_essentials
    description: Essential utilities for image processing
  - url: https://github.com/Fannovel16/comfyui_controlnet_aux
    description: ControlNet auxiliary preprocessors

# Additional Python requirements (will be merged with base)
requirements:
  - imageio>=2.31.0
  - imageio-ffmpeg>=0.4.9
  - moviepy>=1.0.3
  - ffmpeg-python>=0.2.0
  - numpy>=1.24.0
  - pillow>=10.0.0
  - einops>=0.7.0
  - omegaconf>=2.3.0
  - tensorboard>=2.15.0
  - scikit-image>=0.21.0
  - segment-anything>=1.0
  - supervision>=0.16.0
  - yolox>=0.3.0
  - triton>=2.1.0  # For speed optimization with WanVideo

# Workflows to include
workflows:
  - wan-video-txt2vid.json
  - wan-video-img2vid.json
  - wan-video-vid2vid.json
  - wan-video-interpolation.json
  - wan-animate-example.json
  - wan22-i2v-a14b-example.json
  - animate-txt2anim.json
  - animate-img2anim.json
  - animate-motion-transfer.json
  - animate-character-consistency.json

# Models to download (organized by subfolder)
models:
  checkpoints:
    - name: animatediff_v3_sd15
      url: https://huggingface.co/guoyww/animatediff/resolve/main/v3_sd15_mm.ckpt
      filename: animatediff_v3_sd15.ckpt
      subfolder: sd15
    - name: realistic_vision_v5
      url: civitai:130072
      filename: realistic_vision_v5.safetensors
      subfolder: sd15
    - name: animatediff_lightning_4step
      url: https://huggingface.co/ByteDance/AnimateDiff-Lightning/resolve/main/animatediff_lightning_4step_diffusers.safetensors
      filename: animatediff_lightning_4step.safetensors
      subfolder: sd15
    - name: sd_turbo
      url: https://huggingface.co/stabilityai/sd-turbo/resolve/main/sd_turbo.safetensors
      filename: sd_turbo.safetensors
      subfolder: sd15
  motion_models:
    - name: mm_sd_v15
      url: https://huggingface.co/guoyww/animatediff/resolve/main/mm_sd_v15.ckpt
      filename: mm_sd_v15.ckpt
    - name: mm_sd_v15_v2
      url: https://huggingface.co/guoyww/animatediff/resolve/main/mm_sd_v15_v2.ckpt
      filename: mm_sd_v15_v2.ckpt
    - name: v3_sd15_mm
      url: https://huggingface.co/guoyww/animatediff/resolve/main/v3_sd15_mm.ckpt
      filename: v3_sd15_mm.ckpt
    - name: mm_sdxl_v10_beta
      url: https://huggingface.co/guoyww/animatediff/resolve/main/mm_sdxl_v10_beta.ckpt
      filename: mm_sdxl_v10_beta.ckpt
    - name: animatediff_lightning_4step_motion
      url: https://huggingface.co/ByteDance/AnimateDiff-Lightning/resolve/main/animatediff_lightning_4step_motion.ckpt
      filename: animatediff_lightning_4step_motion.ckpt
    - name: temporaldiff_v1
      url: https://huggingface.co/CiaraRowles/TemporalDiff/resolve/main/temporaldiff-v1-animatediff.ckpt
      filename: temporaldiff_v1.ckpt
  vae:
    - name: vae-ft-mse
      url: https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.safetensors
      filename: vae-ft-mse-840000-ema-pruned.safetensors
      subfolder: sd15
    - name: sdxl_vae
      url: https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/resolve/main/sdxl_vae.safetensors
      filename: sdxl_vae.safetensors
      subfolder: sdxl
  controlnet:
    - name: control_v11f1e_sd15_tile
      url: https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11f1e_sd15_tile.pth
      filename: control_v11f1e_sd15_tile.pth
      subfolder: sd15
    - name: control_v11p_sd15_openpose
      url: https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11p_sd15_openpose.pth
      filename: control_v11p_sd15_openpose.pth
      subfolder: sd15
    - name: control_v11f1p_sd15_depth
      url: https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11f1p_sd15_depth.pth
      filename: control_v11f1p_sd15_depth.pth
      subfolder: sd15
  loras:
    - name: v2_lora_pan_left
      url: https://huggingface.co/guoyww/animatediff/resolve/main/v2_lora_PanLeft.ckpt
      filename: v2_lora_pan_left.ckpt
      subfolder: sd15
    - name: v2_lora_pan_right
      url: https://huggingface.co/guoyww/animatediff/resolve/main/v2_lora_PanRight.ckpt
      filename: v2_lora_pan_right.ckpt
      subfolder: sd15
    - name: v2_lora_zoom_in
      url: https://huggingface.co/guoyww/animatediff/resolve/main/v2_lora_ZoomIn.ckpt
      filename: v2_lora_zoom_in.ckpt
      subfolder: sd15
    - name: v2_lora_zoom_out
      url: https://huggingface.co/guoyww/animatediff/resolve/main/v2_lora_ZoomOut.ckpt
      filename: v2_lora_zoom_out.ckpt
      subfolder: sd15
  # WanVideo models
  wanvideo:
    - name: wan22_animate_14b
      url: https://huggingface.co/Wan-AI/Wan2.2-Animate-14B/resolve/main/Wan2_2_Animate_14B_bf16.safetensors
      filename: Wan2_2_Animate_14B_bf16.safetensors
    - name: wan22_i2v_a14b_high_fp8
      url: https://huggingface.co/kijai/WanVideo_pruned/resolve/main/Wan2_2-I2V-A14B-HIGH_fp8_e4m3fn_scaled_KJ.safetensors
      filename: Wan2_2-I2V-A14B-HIGH_fp8_e4m3fn_scaled_KJ.safetensors
    - name: wan22_i2v_a14b_low_fp8
      url: https://huggingface.co/kijai/WanVideo_pruned/resolve/main/Wan2_2-I2V-A14B-LOW_fp8_e4m3fn_scaled_KJ.safetensors
      filename: Wan2_2-I2V-A14B-LOW_fp8_e4m3fn_scaled_KJ.safetensors
    - name: wan21_vae
      url: https://huggingface.co/Wan-AI/WanVideo/resolve/main/Wan2_1_VAE_bf16.safetensors
      filename: Wan2_1_VAE_bf16.safetensors
    - name: lightx2v_i2v_14b_lora
      url: https://huggingface.co/kijai/WanVideo_pruned/resolve/main/lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors
      filename: lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors
  # CLIP Vision models
  clip_vision:
    - name: clip_vision_h
      url: https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors
      filename: clip_vision_h.safetensors
  # SAM2 models for segmentation
  sam:
    - name: sam2_hiera_base_plus
      url: https://dl.fbaipublicfiles.com/segment_anything_2/072824/sam2_hiera_base_plus.pt
      filename: sam2_hiera_base_plus.safetensors
  # YOLOX models for detection
  yolox:
    - name: yolox_l
      url: https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.0/yolox_l.pth
      filename: yolox_l.torchscript.pt
  # DWPose preprocessor models
  dwpose:
    - name: dw_ll_ucoco_384
      url: https://huggingface.co/yzd-v/DWPose/resolve/main/dw-ll_ucoco_384.pth
      filename: dw-ll_ucoco_384_bs5.torchscript.pt
  # T5 Text encoders
  text_encoders:
    - name: umt5_xxl_fp16
      url: https://huggingface.co/mcmonkey/google_umt5-xxl_encoderonly_fp16/resolve/main/umt5_xxl_fp16.safetensors
      filename: umt5_xxl_fp16.safetensors

# Environment variables (override base)
env_vars:
  DOWNLOAD_MODELS: "false"
  AUTO_UPDATE: "false"
  VARIANT_NAME: "video"
  COMFYUI_ARGS: ""  # Default memory management (auto) works best for 24GB cards