name: Build ComfyUI Docker Images

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'comfyui/**'
    tags:
      - 'comfyui-v*'
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
    inputs:
      variant:
        description: 'Variant to build (base, sdxl-pony, flux, video, or all)'
        required: true
        default: 'all'
        type: choice
        options:
          - base
          - sdxl-pony
          - flux
          - video
          - all
      tag_name:
        description: 'Docker image tag (optional)'
        required: false
        default: ''

env:
  REGISTRY: ghcr.io

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set build matrix
        id: set-matrix
        run: |
          if [ "${{ github.event.inputs.variant }}" = "all" ] || [ -z "${{ github.event.inputs.variant }}" ]; then
            echo "matrix={\"variant\":[\"base\",\"sdxl-pony\",\"flux\",\"video\"]}" >> $GITHUB_OUTPUT
          else
            echo "matrix={\"variant\":[\"${{ github.event.inputs.variant }}\"]}" >> $GITHUB_OUTPUT
          fi

  build:
    needs: build-matrix
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix: ${{fromJson(needs.build-matrix.outputs.matrix)}}
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/runpod-comfyui
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ matrix.variant }}
            type=raw,value=${{ matrix.variant }}-{{sha}},enable=${{ github.ref != 'refs/heads/main' }}
            type=raw,value=latest,enable=${{ matrix.variant == 'base' && github.ref == 'refs/heads/main' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./comfyui
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.variant }}
          cache-to: type=gha,mode=max,scope=${{ matrix.variant }}
          build-args: |
            CONFIG=${{ matrix.variant }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            VCS_REF=${{ github.sha }}
            BUILDKIT_INLINE_CACHE=1